### ISSUE TITLE
Are crowd annotations available?

### ISSUE THREAD

**Issue by jnothman** [lasigeBioTM/HPO_Crowd_Annotation_Experiment#1]
Hi, Thanks for your interesting experiment. It seems your [notebook](https://github.com/lasigeBioTM/HPO_Crowd_Annotation_Experiment/blob/master/compare_annotations_with_gold_standard.ipynb) references `aggregated_results_0.{3,5,7,8}`, which are not provided. It seems the pre-aggregation results in `annotation_results_simple_tsv` ([referenced here](https://github.com/lasigeBioTM/HPO_Crowd_Annotation_Experiment/blob/master/create_aggregate_annotations.py#L5)) are not provided either. In order to better understand your results, it would be great if you could upload the data. Thanks.

**Comment by LLCampos** [comment]
Hello. It's been a long time and I do not work in research anymore but I'll take a look when I have the time. :wink:

**Comment by LLCampos** [comment]
@AndreLamurias, hi. :smiley: Do you have these data? I'm not finding it anywhere.

**Comment by AndreLamurias** [comment]
Sorry, can't find it either

**Comment by jnothman** [comment]
Okay, thanks for trying.
